import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const publicSan = Public_Sans({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={publicSan.className}>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
